/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.luisjrz96.streaming.birthsgenerator.models;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BirthInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3810763422022663777L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BirthInfo\",\"namespace\":\"com.luisjrz96.streaming.birthsgenerator.models\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"},{\"name\":\"state\",\"type\":\"string\"},{\"name\":\"gender\",\"type\":{\"type\":\"enum\",\"name\":\"Gender\",\"symbols\":[\"MALE\",\"FEMALE\"]}},{\"name\":\"date\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"height\",\"type\":\"int\"},{\"name\":\"weight\",\"type\":\"float\",\"logicalType\":\"decimal\",\"precision\":4,\"scale\":2}],\"version\":\"1.0\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BirthInfo> ENCODER =
      new BinaryMessageEncoder<BirthInfo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BirthInfo> DECODER =
      new BinaryMessageDecoder<BirthInfo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BirthInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BirthInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BirthInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BirthInfo>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BirthInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BirthInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BirthInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BirthInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence lastName;
  @Deprecated public java.lang.CharSequence country;
  @Deprecated public java.lang.CharSequence state;
  @Deprecated public com.luisjrz96.streaming.birthsgenerator.models.Gender gender;
  @Deprecated public long date;
  @Deprecated public int height;
  @Deprecated public float weight;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BirthInfo() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param lastName The new value for lastName
   * @param country The new value for country
   * @param state The new value for state
   * @param gender The new value for gender
   * @param date The new value for date
   * @param height The new value for height
   * @param weight The new value for weight
   */
  public BirthInfo(java.lang.CharSequence name, java.lang.CharSequence lastName, java.lang.CharSequence country, java.lang.CharSequence state, com.luisjrz96.streaming.birthsgenerator.models.Gender gender, java.lang.Long date, java.lang.Integer height, java.lang.Float weight) {
    this.name = name;
    this.lastName = lastName;
    this.country = country;
    this.state = state;
    this.gender = gender;
    this.date = date;
    this.height = height;
    this.weight = weight;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return lastName;
    case 2: return country;
    case 3: return state;
    case 4: return gender;
    case 5: return date;
    case 6: return height;
    case 7: return weight;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: lastName = (java.lang.CharSequence)value$; break;
    case 2: country = (java.lang.CharSequence)value$; break;
    case 3: state = (java.lang.CharSequence)value$; break;
    case 4: gender = (com.luisjrz96.streaming.birthsgenerator.models.Gender)value$; break;
    case 5: date = (java.lang.Long)value$; break;
    case 6: height = (java.lang.Integer)value$; break;
    case 7: weight = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return The value of the 'lastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }


  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'country' field.
   * @return The value of the 'country' field.
   */
  public java.lang.CharSequence getCountry() {
    return country;
  }


  /**
   * Sets the value of the 'country' field.
   * @param value the value to set.
   */
  public void setCountry(java.lang.CharSequence value) {
    this.country = value;
  }

  /**
   * Gets the value of the 'state' field.
   * @return The value of the 'state' field.
   */
  public java.lang.CharSequence getState() {
    return state;
  }


  /**
   * Sets the value of the 'state' field.
   * @param value the value to set.
   */
  public void setState(java.lang.CharSequence value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'gender' field.
   * @return The value of the 'gender' field.
   */
  public com.luisjrz96.streaming.birthsgenerator.models.Gender getGender() {
    return gender;
  }


  /**
   * Sets the value of the 'gender' field.
   * @param value the value to set.
   */
  public void setGender(com.luisjrz96.streaming.birthsgenerator.models.Gender value) {
    this.gender = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public long getDate() {
    return date;
  }


  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(long value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'height' field.
   * @return The value of the 'height' field.
   */
  public int getHeight() {
    return height;
  }


  /**
   * Sets the value of the 'height' field.
   * @param value the value to set.
   */
  public void setHeight(int value) {
    this.height = value;
  }

  /**
   * Gets the value of the 'weight' field.
   * @return The value of the 'weight' field.
   */
  public float getWeight() {
    return weight;
  }


  /**
   * Sets the value of the 'weight' field.
   * @param value the value to set.
   */
  public void setWeight(float value) {
    this.weight = value;
  }

  /**
   * Creates a new BirthInfo RecordBuilder.
   * @return A new BirthInfo RecordBuilder
   */
  public static com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder newBuilder() {
    return new com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder();
  }

  /**
   * Creates a new BirthInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BirthInfo RecordBuilder
   */
  public static com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder newBuilder(com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder other) {
    if (other == null) {
      return new com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder();
    } else {
      return new com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder(other);
    }
  }

  /**
   * Creates a new BirthInfo RecordBuilder by copying an existing BirthInfo instance.
   * @param other The existing instance to copy.
   * @return A new BirthInfo RecordBuilder
   */
  public static com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder newBuilder(com.luisjrz96.streaming.birthsgenerator.models.BirthInfo other) {
    if (other == null) {
      return new com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder();
    } else {
      return new com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for BirthInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BirthInfo>
    implements org.apache.avro.data.RecordBuilder<BirthInfo> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence lastName;
    private java.lang.CharSequence country;
    private java.lang.CharSequence state;
    private com.luisjrz96.streaming.birthsgenerator.models.Gender gender;
    private long date;
    private int height;
    private float weight;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.lastName)) {
        this.lastName = data().deepCopy(fields()[1].schema(), other.lastName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.country)) {
        this.country = data().deepCopy(fields()[2].schema(), other.country);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.state)) {
        this.state = data().deepCopy(fields()[3].schema(), other.state);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.gender)) {
        this.gender = data().deepCopy(fields()[4].schema(), other.gender);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.date)) {
        this.date = data().deepCopy(fields()[5].schema(), other.date);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.height)) {
        this.height = data().deepCopy(fields()[6].schema(), other.height);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.weight)) {
        this.weight = data().deepCopy(fields()[7].schema(), other.weight);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing BirthInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.luisjrz96.streaming.birthsgenerator.models.BirthInfo other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lastName)) {
        this.lastName = data().deepCopy(fields()[1].schema(), other.lastName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.country)) {
        this.country = data().deepCopy(fields()[2].schema(), other.country);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.state)) {
        this.state = data().deepCopy(fields()[3].schema(), other.state);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.gender)) {
        this.gender = data().deepCopy(fields()[4].schema(), other.gender);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.date)) {
        this.date = data().deepCopy(fields()[5].schema(), other.date);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.height)) {
        this.height = data().deepCopy(fields()[6].schema(), other.height);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.weight)) {
        this.weight = data().deepCopy(fields()[7].schema(), other.weight);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }


    /**
      * Sets the value of the 'lastName' field.
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.lastName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lastName' field.
      * @return This builder.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'country' field.
      * @return The value.
      */
    public java.lang.CharSequence getCountry() {
      return country;
    }


    /**
      * Sets the value of the 'country' field.
      * @param value The value of 'country'.
      * @return This builder.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder setCountry(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.country = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'country' field has been set.
      * @return True if the 'country' field has been set, false otherwise.
      */
    public boolean hasCountry() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'country' field.
      * @return This builder.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder clearCountry() {
      country = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'state' field.
      * @return The value.
      */
    public java.lang.CharSequence getState() {
      return state;
    }


    /**
      * Sets the value of the 'state' field.
      * @param value The value of 'state'.
      * @return This builder.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder setState(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.state = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'state' field has been set.
      * @return True if the 'state' field has been set, false otherwise.
      */
    public boolean hasState() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'state' field.
      * @return This builder.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder clearState() {
      state = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'gender' field.
      * @return The value.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.Gender getGender() {
      return gender;
    }


    /**
      * Sets the value of the 'gender' field.
      * @param value The value of 'gender'.
      * @return This builder.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder setGender(com.luisjrz96.streaming.birthsgenerator.models.Gender value) {
      validate(fields()[4], value);
      this.gender = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'gender' field has been set.
      * @return True if the 'gender' field has been set, false otherwise.
      */
    public boolean hasGender() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'gender' field.
      * @return This builder.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder clearGender() {
      gender = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public long getDate() {
      return date;
    }


    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder setDate(long value) {
      validate(fields()[5], value);
      this.date = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder clearDate() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'height' field.
      * @return The value.
      */
    public int getHeight() {
      return height;
    }


    /**
      * Sets the value of the 'height' field.
      * @param value The value of 'height'.
      * @return This builder.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder setHeight(int value) {
      validate(fields()[6], value);
      this.height = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'height' field has been set.
      * @return True if the 'height' field has been set, false otherwise.
      */
    public boolean hasHeight() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'height' field.
      * @return This builder.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder clearHeight() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'weight' field.
      * @return The value.
      */
    public float getWeight() {
      return weight;
    }


    /**
      * Sets the value of the 'weight' field.
      * @param value The value of 'weight'.
      * @return This builder.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder setWeight(float value) {
      validate(fields()[7], value);
      this.weight = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'weight' field has been set.
      * @return True if the 'weight' field has been set, false otherwise.
      */
    public boolean hasWeight() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'weight' field.
      * @return This builder.
      */
    public com.luisjrz96.streaming.birthsgenerator.models.BirthInfo.Builder clearWeight() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BirthInfo build() {
      try {
        BirthInfo record = new BirthInfo();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.lastName = fieldSetFlags()[1] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.country = fieldSetFlags()[2] ? this.country : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.state = fieldSetFlags()[3] ? this.state : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.gender = fieldSetFlags()[4] ? this.gender : (com.luisjrz96.streaming.birthsgenerator.models.Gender) defaultValue(fields()[4]);
        record.date = fieldSetFlags()[5] ? this.date : (java.lang.Long) defaultValue(fields()[5]);
        record.height = fieldSetFlags()[6] ? this.height : (java.lang.Integer) defaultValue(fields()[6]);
        record.weight = fieldSetFlags()[7] ? this.weight : (java.lang.Float) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BirthInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<BirthInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BirthInfo>
    READER$ = (org.apache.avro.io.DatumReader<BirthInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeString(this.lastName);

    out.writeString(this.country);

    out.writeString(this.state);

    out.writeEnum(this.gender.ordinal());

    out.writeLong(this.date);

    out.writeInt(this.height);

    out.writeFloat(this.weight);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8)this.lastName : null);

      this.country = in.readString(this.country instanceof Utf8 ? (Utf8)this.country : null);

      this.state = in.readString(this.state instanceof Utf8 ? (Utf8)this.state : null);

      this.gender = com.luisjrz96.streaming.birthsgenerator.models.Gender.values()[in.readEnum()];

      this.date = in.readLong();

      this.height = in.readInt();

      this.weight = in.readFloat();

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8)this.lastName : null);
          break;

        case 2:
          this.country = in.readString(this.country instanceof Utf8 ? (Utf8)this.country : null);
          break;

        case 3:
          this.state = in.readString(this.state instanceof Utf8 ? (Utf8)this.state : null);
          break;

        case 4:
          this.gender = com.luisjrz96.streaming.birthsgenerator.models.Gender.values()[in.readEnum()];
          break;

        case 5:
          this.date = in.readLong();
          break;

        case 6:
          this.height = in.readInt();
          break;

        case 7:
          this.weight = in.readFloat();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










